/* Renders every piece of text, link and media from site.json.
   Non-coders: edit site.json (or use a CMS on top of it). Do not edit this file. */
(function () {
  'use strict';
  var $ = function (s, r) { return (r || document).querySelector(s); };
  var $$ = function (s, r) { return Array.prototype.slice.call((r || document).querySelectorAll(s)); };
  var page = document.body.dataset.page;
  var home = page === 'home';

  function h(tag, attrs) {
    var e = document.createElement(tag);
    attrs = attrs || {};
    Object.keys(attrs).forEach(function (k) {
      var v = attrs[k];
      if (v === false || v == null) return;
      if (k === 'class') e.className = v;
      else if (k === 'text') e.textContent = v;
      else e.setAttribute(k, v === true ? '' : v);
    });
    for (var i = 2; i < arguments.length; i++) {
      var kids = [].concat(arguments[i]);
      kids.forEach(function (k) { if (k != null && k !== false) e.append(k.nodeType ? k : document.createTextNode(k)); });
    }
    return e;
  }
  function get(o, path) { return path.split('.').reduce(function (a, k) { return a == null ? a : a[k]; }, o); }

  // No decorative artwork in this tier: an empty media slot is a plain bordered
  // monogram tile (initials, type only), not an illustration or diagram.
  function art(label) {
    var initials = String(label || '').replace(/[.,()]/g, '').split(/\s+/)
      .filter(function (w) { return /^[A-Za-z]/.test(w) && !/^(Ph|DBA|Dr)$/i.test(w); })
      .map(function (w) { return w[0]; }).slice(0, 2).join('').toUpperCase();
    return h('div', { class: 'ph' }, h('span', { text: initials }));
  }
  function media(src, label, cls) {
    var wrap = h('div', { class: 'slot ' + (cls || '') });
    var ph = art(label);
    wrap.append(ph);
    if (!src) return wrap;
    var el = h('img', { alt: label || '', loading: 'lazy' });
    el.addEventListener('load', function () { ph.remove(); });
    el.addEventListener('error', function () { el.remove(); });
    el.src = src;
    wrap.prepend(el);
    return wrap;
  }

  function navItem(n) {
    if (!n.children) return h('a', { href: n.href || n.page }, n.label);
    var item = h('div', { class: 'nav-item' });
    var trigger = h('button', { class: 'nav-trigger', type: 'button', 'aria-expanded': 'false' }, n.label, h('span', { class: 'nav-caret', 'aria-hidden': 'true' }, ''));
    var sub = h('div', { class: 'submenu' }, n.children.map(function (c) {
      return h('a', { href: c.href || c.page }, c.label);
    }));
    trigger.addEventListener('click', function (e) {
      e.stopPropagation();
      var open = item.classList.toggle('open');
      trigger.setAttribute('aria-expanded', open ? 'true' : 'false');
      $$('.nav-item.open').forEach(function (o) { if (o !== item) { o.classList.remove('open'); $('.nav-trigger', o).setAttribute('aria-expanded', 'false'); } });
    });
    item.append(trigger, sub);
    return item;
  }

  function renderChrome(D) {
    var nav = D.nav.map(navItem);
    nav.push(h('a', { class: 'nav-cta', href: 'portal.html' }, D.sections.portalNav || 'Portal'));
    var brand = h('a', { class: 'brand', href: 'index.html', 'aria-label': D.site.name + ', home' });
    brand.innerHTML = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 13V3h18v18h-8" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linejoin="miter"/><path d="M3 19h6" fill="none" stroke="var(--terracotta)" stroke-width="2.2"/></svg>';
    brand.append(D.site.name);
    var burger = h('button', { class: 'burger', type: 'button', 'aria-label': 'Menu', 'aria-expanded': 'false' }, h('span'), h('span'), h('span'));
    var navEl = h('nav', { 'aria-label': 'Primary' }, nav);
    burger.addEventListener('click', function () {
      var open = document.body.classList.toggle('nav-open');
      burger.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
    document.addEventListener('click', function () {
      $$('.nav-item.open').forEach(function (o) { o.classList.remove('open'); $('.nav-trigger', o).setAttribute('aria-expanded', 'false'); });
    });
    $('#site-header').append(h('div', { class: 'bar wrap' }, brand, navEl, burger));
    var c = D.contact;
    $('#site-footer').append(h('div', { class: 'cols wrap' },
      h('div', {}, h('p', { class: 'fname', text: D.site.name }),
        h('p', {}, (c.pressLabel || 'Inquiries and press') + ': ', h('a', { href: 'mailto:' + c.press }, c.press)),
        h('p', {}, (c.dealsLabel || 'Investment inquiries') + ': ', h('a', { href: 'mailto:' + c.deals }, c.deals))),
      h('div', {}, h('p', {}, h('a', { href: c.linkedin }, 'LinkedIn')), h('p', {}, h('a', { href: c.privacy }, 'Privacy policy')), h('p', {}, h('a', { href: c.terms }, 'Terms of use')))));
  }

  // Original line-art diagrams, one per theme -- not stock photography, so there's
  // no licensing question, and the thin-stroke navy/orange style matches the rest
  // of the site rather than sitting on top of it as decoration.
  var THEME_DIAGRAMS = [
    // Precision nutrition: a plate viewed in plan, with a measured/targeted center
    '<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">' +
      '<circle cx="32" cy="32" r="26" stroke="currentColor" stroke-width="1.4" opacity=".35"/>' +
      '<circle cx="32" cy="32" r="16" stroke="currentColor" stroke-width="1.4" opacity=".6"/>' +
      '<circle cx="32" cy="32" r="3.4" fill="var(--terracotta)"/>' +
      '<path d="M32 6v6M32 52v6M6 32h6M52 32h6" stroke="currentColor" stroke-width="1.4" opacity=".5"/>' +
    '</svg>',
    // Intelligent health: a pulse line running through connected nodes
    '<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">' +
      '<circle cx="32" cy="32" r="26" stroke="currentColor" stroke-width="1.4" opacity=".35"/>' +
      '<path d="M12 34h8l4-10 6 18 5-13 3 5h14" stroke="var(--terracotta)" stroke-width="1.8" stroke-linejoin="round" stroke-linecap="round"/>' +
      '<circle cx="20" cy="34" r="2" fill="currentColor"/>' +
      '<circle cx="44" cy="34" r="2" fill="currentColor"/>' +
    '</svg>',
    // Food & medicine: two overlapping fields converging, a leaf and a cross
    '<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">' +
      '<circle cx="25" cy="32" r="18" stroke="currentColor" stroke-width="1.4" opacity=".45"/>' +
      '<circle cx="39" cy="32" r="18" stroke="currentColor" stroke-width="1.4" opacity=".45"/>' +
      '<path d="M22 26c6 0 8 4 8 10-6 0-8-4-8-10z" fill="none" stroke="var(--terracotta)" stroke-width="1.5"/>' +
      '<path d="M39 25v14M32 32h14" stroke="var(--terracotta)" stroke-width="1.8" stroke-linecap="round"/>' +
    '</svg>'
  ];

  function renderThemes(D) {
    var m = $('#themes-list'); if (!m) return;
    D.themes.forEach(function (t, i) {
      var icon = h('div', { class: 'theme-icon' });
      icon.innerHTML = THEME_DIAGRAMS[i % THEME_DIAGRAMS.length];
      m.append(h('div', { class: 'theme-row' },
        h('span', { class: 'tnum', text: '0' + (i + 1) }),
        h('div', { class: 'theme-body' },
          h('h3', { class: 'theme-title', text: t.title }),
          h('p', { class: 'theme-copy', text: t.text })),
        icon));
    });
  }

  function renderStats(D) {
    var m = $('#stats'); if (!m) return;
    D.stats.forEach(function (s) {
      m.append(h('div', { class: 'stat' },
        h('b', { text: (s.prefix || '') + s.number + (s.suffix || '') }),
        h('span', { text: s.label })));
    });
  }

  function renderPortfolio(D) {
    var m = $('#pfgrid'); if (!m) return;
    var list = home ? D.portfolio.slice(0, 8) : D.portfolio;
    list.forEach(function (p) {
      m.append(h('a', { class: 'pcard', href: p.url, target: '_blank', rel: 'noopener', 'data-category': p.category || '', 'data-name': (p.name || '').toLowerCase() },
        media(p.media, p.name, 'pcard-media'), h('span', { text: p.name }),
        p.category ? h('small', { text: p.category }) : null));
    });
  }

  // Dynamic filtering + search for the full portfolio grid. Client-side only --
  // fine at this size (a handful of companies); a directory in the hundreds
  // would want this driven server-side instead.
  function renderPortfolioControls(D) {
    var bar = $('#pf-filters'); var grid = $('#pfgrid'); if (!bar || !grid) return;
    var state = { cat: 'All', q: '' };
    var count = h('p', { class: 'result-count' });
    bar.parentNode.insertBefore(count, bar.nextSibling);

    function apply2() {
      var cards = $$('.pcard', grid);
      var shown = 0;
      cards.forEach(function (c) {
        var okCat = state.cat === 'All' || c.dataset.category === state.cat;
        var okQ = !state.q || c.dataset.name.indexOf(state.q) > -1;
        var visible = okCat && okQ;
        c.classList.toggle('hidden', !visible);
        if (visible) shown++;
      });
      count.textContent = shown + (shown === 1 ? ' company' : ' companies');
      var empty = $('.empty-state', grid);
      if (shown === 0 && !empty) grid.append(h('p', { class: 'empty-state', text: 'No companies match those filters.' }));
      if (shown > 0 && empty) empty.remove();
    }

    var chips = ['All'].concat(D.portfolioCategories || []).map(function (catName) {
      var btn = h('button', { class: 'filter-chip' + (catName === 'All' ? ' active' : ''), type: 'button', text: catName });
      btn.addEventListener('click', function () {
        state.cat = catName;
        $$('.filter-chip', bar).forEach(function (b) { b.classList.remove('active'); });
        btn.classList.add('active');
        apply2();
      });
      return btn;
    });
    var searchWrap = h('div', { class: 'search-box' });
    searchWrap.innerHTML = '<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="2"/><path d="M21 21l-4.3-4.3" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';
    var input = h('input', { type: 'search', placeholder: get(D, 'sections.searchPlaceholder') || 'Search' });
    input.addEventListener('input', function () { state.q = input.value.trim().toLowerCase(); apply2(); });
    searchWrap.append(input);

    chips.forEach(function (c) { bar.append(c); });
    bar.append(searchWrap);
    apply2();
  }

  function renderCareers(D) {
    var m = $('#career-list'); if (!m) return;
    D.portfolio.forEach(function (p) {
      m.append(h('a', { class: 'career-row', href: p.url, target: '_blank', rel: 'noopener' },
        media(p.media, p.name, ''),
        h('div', {}, h('span', { class: 'career-name', text: p.name }), p.category ? h('small', { class: 'career-cat', text: p.category }) : null),
        h('span', { class: 'career-cta', text: 'View openings \u2192' })));
    });
  }

  function renderResourceTabs(D) {
    var bar = $('#resource-tabs'); if (!bar) return;
    var tabs = get(D, 'sections.resourcesTabs') || ['News'];
    var panels = $$('.tab-panel', bar.parentNode);
    tabs.forEach(function (label, i) {
      var btn = h('button', { class: 'tab-btn' + (i === 0 ? ' active' : ''), type: 'button', text: label });
      btn.addEventListener('click', function () {
        $$('.tab-btn', bar).forEach(function (b) { b.classList.remove('active'); });
        panels.forEach(function (p) { p.classList.remove('active'); });
        btn.classList.add('active');
        var target = $('[data-panel="' + label + '"]', bar.parentNode);
        if (target) target.classList.add('active');
      });
      bar.append(btn);
    });
  }

  function renderPeople(D) {
    var g = $('#people-grid'); if (!g) return;
    D.people.forEach(function (p) {
      g.append(h('div', { class: 'person' },
        media(p.photo, p.name, 'person-media'),
        h('h3', { text: p.name }),
        p.role ? h('small', { text: p.role }) : null,
        p.bio ? h('p', { text: p.bio }) : null));
    });
  }

  function renderNews(D) {
    var m = $('#news-list') || $('#news'); if (!m) return;
    var list = home ? D.news.slice(0, 3) : D.news;
    list.forEach(function (n) {
      m.append(h('a', { class: 'nrow', href: n.url, target: '_blank', rel: 'noopener' },
        media(n.image, n.title, 'nrow-media'),
        h('div', {}, h('small', { text: n.date + (n.tag ? ' \u00b7 ' + n.tag : '') }), h('strong', { text: n.title }))));
    });
  }

  function renderEcosystemLists(D) {
    var a = $('#anchors'), p = $('#partners'); if (!a && !p) return;
    if (a) D.ecosystem.anchors.forEach(function (x) { a.append(h('li', {}, h('a', { href: x.url, target: '_blank', rel: 'noopener' }, x.name))); });
    if (p) D.ecosystem.partners.forEach(function (x) { p.append(h('li', {}, h('a', { href: x.url, target: '_blank', rel: 'noopener' }, x.name))); });
  }

  function renderContact(D) {
    var m = $('#contact-lines'); if (!m) return;
    var c = D.contact;
    m.append(
      h('p', {}, h('small', { text: c.dealsLabel || 'Investment inquiries' }), h('br'), h('a', { href: 'mailto:' + c.deals }, c.deals)),
      h('p', {}, h('small', { text: c.pressLabel || 'Inquiries and press' }), h('br'), h('a', { href: 'mailto:' + c.press }, c.press)),
      h('p', {}, h('a', { href: c.linkedin, target: '_blank', rel: 'noopener' }, 'LinkedIn')));
  }

  function renderForm(D) {
    var f = $('#signup'); if (!f) return;
    [['first', 'First name', 'given-name'], ['last', 'Last name', 'family-name'], ['company', 'Company name', 'organization'], ['email', 'Email', 'email']].forEach(function (x) {
      f.append(h('div', {}, h('label', { for: 'f-' + x[0], text: x[1] }), h('input', { id: 'f-' + x[0], name: x[0], required: true, autocomplete: x[2], type: x[0] === 'email' ? 'email' : 'text' })));
    });
    var ok = h('p', { class: 'ok', role: 'status' });
    f.append(h('button', { class: 'btn', type: 'submit' }, 'Subscribe'), ok);
    if (D.site.formAction) { f.setAttribute('action', D.site.formAction); f.setAttribute('method', 'post'); }
    else f.addEventListener('submit', function (e) {
      e.preventDefault();
      ok.textContent = 'Thanks, ' + $('#f-first').value + '. You are on the list.';
      f.reset();
    });
  }

  function apply(D) {
    $$('[data-text]').forEach(function (e) { var v = get(D, e.dataset.text); if (v != null) e.textContent = v; });
    renderChrome(D);
    renderThemes(D);
    renderStats(D);
    renderPortfolio(D);
    renderPortfolioControls(D);
    renderCareers(D);
    renderResourceTabs(D);
    renderPeople(D);
    renderNews(D);
    renderEcosystemLists(D);
    renderContact(D);
    renderForm(D);
    window.TMG_READY = true;
    document.dispatchEvent(new Event('tmg:ready'));
  }

  if (window.TMG_DATA) apply(window.TMG_DATA);
  else fetch('site.json').then(function (r) { return r.json(); }).then(apply)
    .catch(function (e) {
      document.body.insertAdjacentHTML('afterbegin', '<p style="padding:90px 24px">Could not load site.json. Serve the folder over http instead of opening the file directly.</p>');
      console.error(e);
    });
})();
