/* Renders every piece of text, link and media from site.json.
   Non-coders: edit site.json (or use a CMS on top of it). Do not edit this file. */
(function () {
  'use strict';
  var $ = function (s, r) { return (r || document).querySelector(s); };
  var $$ = function (s, r) { return Array.prototype.slice.call((r || document).querySelectorAll(s)); };
  var page = document.body.dataset.page;
  var home = page === 'home';

  function h(tag, attrs) {
    var e = document.createElement(tag);
    attrs = attrs || {};
    Object.keys(attrs).forEach(function (k) {
      var v = attrs[k];
      if (v === false || v == null) return;
      if (k === 'class') e.className = v;
      else if (k === 'text') e.textContent = v;
      else e.setAttribute(k, v === true ? '' : v);
    });
    for (var i = 2; i < arguments.length; i++) {
      var kids = [].concat(arguments[i]);
      kids.forEach(function (k) { if (k != null && k !== false) e.append(k.nodeType ? k : document.createTextNode(k)); });
    }
    return e;
  }
  function get(o, path) { return path.split('.').reduce(function (a, k) { return a == null ? a : a[k]; }, o); }

  // No decorative artwork in this tier: an empty media slot is a plain bordered
  // monogram tile (initials, type only), not an illustration or diagram.
  function art(label) {
    var initials = String(label || '').replace(/[.,()]/g, '').split(/\s+/)
      .filter(function (w) { return /^[A-Za-z]/.test(w) && !/^(Ph|DBA|Dr)$/i.test(w); })
      .map(function (w) { return w[0]; }).slice(0, 2).join('').toUpperCase();
    return h('div', { class: 'ph' }, h('span', { text: initials }));
  }
  function media(src, label, cls) {
    var wrap = h('div', { class: 'slot ' + (cls || '') });
    var ph = art(label);
    wrap.append(ph);
    if (!src) return wrap;
    var el = h('img', { alt: label || '', loading: 'lazy' });
    el.addEventListener('load', function () { ph.remove(); });
    el.addEventListener('error', function () { el.remove(); });
    el.src = src;
    wrap.prepend(el);
    return wrap;
  }

  function renderChrome(D) {
    var nav = D.nav.map(function (n) { return h('a', { href: n.href || n.page }, n.label); });
    nav.push(h('a', { class: 'nav-cta', href: 'contact.html' }, D.sections.contactNav || 'Contact'));
    var brand = h('a', { class: 'brand', href: 'index.html', 'aria-label': D.site.name + ', home' });
    brand.innerHTML = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 13V3h18v18h-8" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linejoin="miter"/><path d="M3 19h6" fill="none" stroke="var(--orange)" stroke-width="2.2"/></svg>';
    brand.append(D.site.name);
    var burger = h('button', { class: 'burger', type: 'button', 'aria-label': 'Menu', 'aria-expanded': 'false' }, h('span'), h('span'), h('span'));
    var navEl = h('nav', { 'aria-label': 'Primary' }, nav);
    burger.addEventListener('click', function () {
      var open = document.body.classList.toggle('nav-open');
      burger.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
    $('#site-header').append(h('div', { class: 'bar wrap' }, brand, navEl, burger));
    var c = D.contact;
    $('#site-footer').append(h('div', { class: 'cols wrap' },
      h('div', {}, h('p', { class: 'fname', text: D.site.name }),
        h('p', {}, (c.pressLabel || 'Inquiries and press') + ': ', h('a', { href: 'mailto:' + c.press }, c.press)),
        h('p', {}, (c.dealsLabel || 'Investment inquiries') + ': ', h('a', { href: 'mailto:' + c.deals }, c.deals))),
      h('div', {}, h('p', {}, h('a', { href: c.linkedin }, 'LinkedIn')), h('p', {}, h('a', { href: c.privacy }, 'Privacy policy')), h('p', {}, h('a', { href: c.terms }, 'Terms of use')))));
  }

  // Home page runs a two-column journal layout: a sticky contents index down the
  // left, sections down the right. This is the structural break from Tier 1's
  // single centered column -- a page architecture change, not a decoration.
  var TOC = [
    ['00', 'Introduction', '#top'],
    ['01', 'sections.themes', '#themes'],
    ['02', 'sections.numbers', '#numbers'],
    ['03', 'sections.portfolio', '#portfolio'],
    ['04', 'sections.news', '#news']
  ];
  function renderContents(D) {
    var m = $('#contents'); if (!m) return;
    TOC.forEach(function (row) {
      var label = row[1].indexOf('sections.') === 0 ? get(D, row[1]) : row[1];
      m.append(h('a', { href: row[2] }, h('span', { class: 'ci-num', text: row[0] }), h('span', { class: 'ci-label', text: label })));
    });
    var links = $$('a', m);
    var targets = TOC.map(function (r) { return document.querySelector(r[2]); }).filter(Boolean);
    if ('IntersectionObserver' in window && targets.length) {
      var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          var idx = targets.indexOf(entry.target);
          if (idx > -1 && entry.isIntersecting) {
            links.forEach(function (l) { l.classList.remove('active'); });
            links[idx].classList.add('active');
          }
        });
      }, { rootMargin: '-40% 0px -50% 0px' });
      targets.forEach(function (t) { io.observe(t); });
    }
  }

  function renderThemes(D) {
    var m = $('#themes-list'); if (!m) return;
    D.themes.forEach(function (t, i) {
      m.append(h('div', { class: 'theme-row' },
        h('span', { class: 'tnum', text: '0' + (i + 1) }),
        h('h3', { class: 'theme-title', text: t.title }),
        h('p', { class: 'theme-copy', text: t.text })));
    });
  }

  function renderStats(D) {
    var m = $('#stats'); if (!m) return;
    D.stats.forEach(function (s) {
      m.append(h('div', { class: 'stat' },
        h('b', { text: (s.prefix || '') + s.number + (s.suffix || '') }),
        h('span', { text: s.label })));
    });
  }

  function renderPortfolio(D) {
    var m = $('#pfgrid'); if (!m) return;
    var list = home ? D.portfolio.slice(0, 8) : D.portfolio;
    list.forEach(function (p) {
      m.append(h('a', { class: 'pcard', href: p.url, target: '_blank', rel: 'noopener' },
        media(p.media, p.name, 'pcard-media'), h('span', { text: p.name })));
    });
  }

  function renderPeople(D) {
    var g = $('#people-grid'); if (!g) return;
    D.people.forEach(function (p) {
      g.append(h('div', { class: 'person' },
        media(p.photo, p.name, 'person-media'),
        h('h3', { text: p.name }),
        p.role ? h('small', { text: p.role }) : null,
        p.bio ? h('p', { text: p.bio }) : null));
    });
  }

  function renderNews(D) {
    var m = $('#news-list') || $('#news'); if (!m) return;
    var list = home ? D.news.slice(0, 3) : D.news;
    list.forEach(function (n) {
      m.append(h('a', { class: 'nrow', href: n.url, target: '_blank', rel: 'noopener' },
        media(n.image, n.title, 'nrow-media'),
        h('div', {}, h('small', { text: n.date + (n.tag ? ' \u00b7 ' + n.tag : '') }), h('strong', { text: n.title }))));
    });
  }

  function renderEcosystemLists(D) {
    var a = $('#anchors'), p = $('#partners'); if (!a && !p) return;
    if (a) D.ecosystem.anchors.forEach(function (x) { a.append(h('li', {}, h('a', { href: x.url, target: '_blank', rel: 'noopener' }, x.name))); });
    if (p) D.ecosystem.partners.forEach(function (x) { p.append(h('li', {}, h('a', { href: x.url, target: '_blank', rel: 'noopener' }, x.name))); });
  }

  function renderContact(D) {
    var m = $('#contact-lines'); if (!m) return;
    var c = D.contact;
    m.append(
      h('p', {}, h('small', { text: c.dealsLabel || 'Investment inquiries' }), h('br'), h('a', { href: 'mailto:' + c.deals }, c.deals)),
      h('p', {}, h('small', { text: c.pressLabel || 'Inquiries and press' }), h('br'), h('a', { href: 'mailto:' + c.press }, c.press)),
      h('p', {}, h('a', { href: c.linkedin, target: '_blank', rel: 'noopener' }, 'LinkedIn')));
  }

  function renderForm(D) {
    var f = $('#signup'); if (!f) return;
    [['first', 'First name', 'given-name'], ['last', 'Last name', 'family-name'], ['company', 'Company name', 'organization'], ['email', 'Email', 'email']].forEach(function (x) {
      f.append(h('div', {}, h('label', { for: 'f-' + x[0], text: x[1] }), h('input', { id: 'f-' + x[0], name: x[0], required: true, autocomplete: x[2], type: x[0] === 'email' ? 'email' : 'text' })));
    });
    var ok = h('p', { class: 'ok', role: 'status' });
    f.append(h('button', { class: 'btn', type: 'submit' }, 'Subscribe'), ok);
    if (D.site.formAction) { f.setAttribute('action', D.site.formAction); f.setAttribute('method', 'post'); }
    else f.addEventListener('submit', function (e) {
      e.preventDefault();
      ok.textContent = 'Thanks, ' + $('#f-first').value + '. You are on the list.';
      f.reset();
    });
  }

  function apply(D) {
    $$('[data-text]').forEach(function (e) { var v = get(D, e.dataset.text); if (v != null) e.textContent = v; });
    renderChrome(D);
    renderContents(D);
    renderThemes(D);
    renderStats(D);
    renderPortfolio(D);
    renderPeople(D);
    renderNews(D);
    renderEcosystemLists(D);
    renderContact(D);
    renderForm(D);
    window.TMG_READY = true;
    document.dispatchEvent(new Event('tmg:ready'));
  }

  if (window.TMG_DATA) apply(window.TMG_DATA);
  else fetch('site.json').then(function (r) { return r.json(); }).then(apply)
    .catch(function (e) {
      document.body.insertAdjacentHTML('afterbegin', '<p style="padding:90px 24px">Could not load site.json. Serve the folder over http instead of opening the file directly.</p>');
      console.error(e);
    });
})();
